const en = {
  listIsEmpty: 'List is empty',
  no: 'No',
  yes: 'Yes',
  cancel: 'Cancel',
  selectDate: 'Select Date',
  didRecvCode: "Didn't receive code? Resend",
  contact: 'Contact',
  contactLable: 'Fill in your phone number and location',
  phoneNumber: 'Phone Number',
  state: 'State',
  Country: 'Country',
  home: 'Home',
  profile: 'Profile',
  login: 'Login',
  logout: 'Logout',
  continuenWithFacebook: 'Continue with Facebook',
  continuenWithGoogle: 'Continue with Google',
  continuenWithApple: 'Continue with Apple',
  continuenWithEmail: 'Continue with Email',
  signUp: 'Sign Up',
  algoace: 'Algoace',
  submit: 'Submit',
  welcomeBack: 'Welcome Back',
  selectCriteria: 'Select your criteria',
  signInLabel: 'Fill out your email address and password',
  tapToProceed: 'Tap to proceed',
  email: 'Email',
  forgotPasswordsmall: 'Forgot password?',
  resendCode: 'Resend code',
  password: 'Password',
  signUpLabel: 'Fill in your personal information',
  firstName: 'First Name',
  lastName: 'Last Name',
  emailAddress: 'Email Address',
  continue: 'Continue',
  dob: 'Date of birth',
  forgotPasswordBold: 'Forgot Your Password?',
  forgotChangePasswordLable: 'Forgot password, please reset password, and confirm code via email.',
  forgotPasswordLable: 'No worries! Enter your email below, and we’ll help you reset it in no time.',
  resetPassword: 'Reset Password',
  reEnterPassword: 'Re-enter new password',
  confirmationCode: 'Confirmation code',
  confirmSignUp: 'Confirm Sign Up',
  verificationSentCode: 'Please enter the 6-digit code we sent to your email to verify your account.',
  oops: 'Oops!',
  errorBoundaryLable: 'Something went wrong try again later',
  tryAgain: 'Try again',
  appLabel: 'Pupspotter',
  changeLanguage: 'Change language',
  MESSAGES: {
    emailRequired: 'Email is required',
    passwordRequired: 'Password is required',
    firstNameRequired: 'First Name is required',
    firstNameLessLength: 'First Name should be less then 30 characters',
    lastNameLessLength: 'Last Name should be less then 30 characters',
    firstNameShort: 'First name too short',
    lastNameShort: 'Last name too short',
    otpLength: 'OTP must be exactly 6 characters',
    otpRequired: 'OTP required',
    lastNameRequired: 'Last Name is required',
    emailInvalid: 'Email is invalid',
    passwordInvalid: 'Password is invalid',
    firstNameInvalid: 'First Name is invalid',
    lastNameInvalid: 'Last Name is invalid',
    passwordNotMatch: 'Password does not match',
    passwordLength: 'Invalid password it should on UpperCase, lowerCase, letter and one number',
  },


  // new text
  loginHeading: 'Ready To Test Your Medical Skills',
  loginSubHeading: 'Sign in to access tailored quizzes, track your progress, and challenge yourself daily.',
  signupHeading: 'Sign Up and Begin Your Quiz Adventure',
  signupSubHeading: 'Join us to unlock personalized quizzes, track your progress, and elevate your medical knowledge.',
  verificationTitle: 'Enter Your Verification Code',
  statistics: 'Statistics',
  myStudy: 'My Study',
  explore: 'Explore'

};

export default en;
export type Translations = typeof en;
