export const queryKey = {
    GET_USER: 'getUser',
    SEARCH_USERS: 'searchUsers',
    FOLLOWER_LIST: 'followerList',
    FOLLOWING_LIST: 'followingList',
    CHECK_CONNECTION: 'checkConnection',
    REQUEST_LIST: 'requestsList',
    GET_PROFILE: 'getProfile',
    GET_BLOCKED_USER: 'getBlockedUser',
    GET_POSTS: 'getPosts',
    GET_MENU_POSTS: 'getMenuPosts',
    GET_SINGLE_POST: 'getSinglePost',
    GET_POST_BY_ID: 'getPostById',
    GET_USER_POSTS: 'getUserPosts',
    GET_USER_SAVED_POSTS: 'getUserSavedPosts',
    GET_USER_ARCHIVED_POSTS: 'getUserArchivedPosts',
    GET_COMMENTS: 'getComments',
    GET_BUSINESS_POSTS: 'getBusinessPosts',
    POST_LIKES: 'postLikes',
    GET_SHARE_USERS: 'getShareUsers',
    GET_POST_VIEWS: 'getPostViews',
    GET_NOTIFICATIONS: 'getNotifications',
    GET_FRIENDS_POSTS: 'getFriendsPosts',
    GET_UNREAD_COUNTS: 'getUnreadCounts',
  };
  