/*
 ** SVGS icons
 */
export const SVG = {
  BackIcon: require('./back.svg').default,
  CalenderIcon: require('./calender.svg').default,
  CameraIcon: require('./camera.svg').default,
  EyeOnIcon: require('./eyeOn.svg').default,
  EyeOffIcon: require('./eyeOff.svg').default,
  HomeIcon: require('./home.svg').default,
  ProfileIcon: require('./profile.svg').default,
  DropDownIcon: require('./dropDown.svg').default,
  DropUpIcon: require('./dropUp.svg').default,
  UserIcon: require('./user.svg').default,
  AppleIcon: require('./apple.svg').default,
  BackArrowIcon: require('./backArrow.svg').default,
  GoogleIcon: require('./google.svg').default,
  StatisticsIcon: require('./statistics').default,
  MyStudyIcon: require('./myStudy.svg').default,
  ExploreIcon: require('./explore.svg').default,
  NotificationIcon: require('./notification.svg').default,
  SearchIcon: require('./search.svg').default,
  FilterIcon: require('./filter.svg').default,
  pharmaIcon: require('./pharma.svg').default,
  StaticsIcon: require('./statics.svg').default,
  HeartIcon: require('./heart.svg').default,
  SkinIcon: require('./skin.svg').default,
  PlayIcon: require('./play.svg').default,
  PlusIcon: require('./plus.svg').default,
  BinIcon: require('./bin.svg').default,
  CrossIcon: require('./cross.svg').default,
  Calendar2Icon: require('./calendar2.svg').default,
  Tick: require('./tick.svg').default,
  Dot: require('./dot.svg').default,
};
